apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-vj
  labels:
     apps: deployapp
spec:
    replicas: 2
    strategy:
         type: RollingUpdate
    selector:
          matchLabels:
            app: deployapp
    templete:
        metadata:
          labels:
            app: deployapp
        spec:
          containers:
             - name: frontendapp
               image: vaibhavjorvekar/frontendrds
               ports:
                 - containerPort: 80
                   protocol: TCP
               resources:
                 requests:
                      memory: "64Mi"
                      cpu: "125m"
                 limits:
                      memory: "128Mi"
                      cpu: "250m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    kind: Deployment
    name: deployment
  minReplicas: 1
  maxreplicas: 4
  metrics:
  - type: Resource
    resoource:
      name: cpu
      target:
      type: Utilization
      averageUtilization: 50