apiVersion: apps/v1
kind:  Deployment
metadata: 
  name: frontend
  labels:
    app: frontendapp
spec:
    strategy:
      type: RollingUpdate
    selector: 
      matchLabels: 
          app: frontendapp
    replicas: 2
    template:
      metadata:
        labels:
          name: httpd
          app: frontendapp
      spec:
        containers:
          - name: httpdapp
            image: vaibhavjorvekar/frontendrds
            ports:
                - containerPort: 80
                  protocol: TCP
                  
