apiVersion: v1
kind: Service
metadata: 
  name: loadbalancersrv
spec:
  type: LoadBalancer
  selector:
    app: frontendapp
  ports:
    - port: 80
      targetPort: 80
      name: httpd
      protocol: TCP
