apiVersion: apps/v1
kind:  Deployment
metadata: 
  name: vaibhav-j    
  labels:
    app: vaibhav
spec:
    strategy:
      type: RollingUpdate
      rollingUpdate:
            maxSurge: 1  
            maxUnavailable: 1 
    selector: 
      #matchExpressions:      
         #  -  { key: app, operator: In , values: [rsapp,  new-app]}
         #   -  { key: app, operator: Exists}
      matchLabels: 
          app: vaibhav
    replicas: 5
    template:
      metadata:
        labels:
          name: nginxapp
          app: vaibhav
      spec:
        containers:
          - name: nginxapp
            image: tomcat
            ports:
                - containerPort: 80
                  protocol: TCP
