apiVersion: v1
kind: ReplicationController
metadata:
  name: vaibhs
  labels:
    app: vaibhs
spec: 
    selector: 
      app: vaibhs 
    replicas: 3
    template:   
      metadata:
        labels:
          name: nginxapp
          app: rpcapp
      spec:
        containers:
          - name: nginxapp
            image: nginx:latest 
            ports:
                - containerPort: 80
                  protocol: TCP
