apiVersion: apps/v1
kind:  StatefulSet
metadata: 
  name: VJ
  labels:
    app: VJ
spec:
    selector: 
      matchLabels: 
          app: VJ
    replicas: 6
    template:
      metadata:
        labels:
          name: vaibhs
          app: VJ
      spec:
        containers:
          - name: mysql
            image: mysql
            ports:
                - containerPort: 3306
                  protocol: TCP
            env:
                 - name: MYSQL_ROOT_PASSWORD
                   value: "1234"
