apiVersion: apps/v1
kind:  StatefulSet
metadata: 
  name: vj
  labels:
    app: vaibhs
spec:
    selector: 
      matchLabels: 
          app: vaibhs
    replicas: 4
    template:
      metadata:
        labels:
          name: vj
          app: vaibhs
      spec:
        containers:
          - name: mysql
            image: mysql
            ports:
                - containerPort: 3306
                  protocol: TCP
            env:
                 - name: MYSQL_ROOT_PASSWORD
                   value: "1234"
